---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        # uses: docker/login-action@v1
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # uses: actions/checkout@v2
        uses: actions/checkout@v4

      # - name: PreTest
        # run: until docker run --rm --link adminpanel2-app-api-db-1:pg --net 172.18.0.2 postgres:9.5 pg_isready -U postgres -h pg; do sleep 1; done
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        # run: docker-compose run --rm app sh -c "python manage.py  test"
      # - name: Lint
        # run: docker-compose run --rm app sh -c "flake8"